#plot 'stderr.keimola' u 1:3 w lp t 'speed', 'stderr.keimola' u 1:4 w l t 'pieceidx', 'stderr.keimola' u 1:5 w lp t 'angle', 'stderr.keimola' u 1:6 w l t 'angular speed', 'stderr.keimola' u 1:7 w l t 'throttle'
#plot 'stderr.germany' u 1:3 w lp t 'speed', 'stderr.germany' u 1:4 w l t 'pieceidx', 'stderr.germany' u 1:5 w lp t 'angle', 'stderr.germany' u 1:6 w l t 'angular speed', 'stderr.germany' u 1:7 w l t 'throttle'
#plot 'stderr.usa' u 1:3 w lp t 'speed', 'stderr.usa' u 1:4 w l t 'pieceidx', 'stderr.usa' u 1:5 w p lt 'angle', 'stderr.usa' u 1:6 w l t 'angular speed', 'stderr.usa' u 1:7 w l t 'throttle'
#plot 'stderr.france' u 1:3 w lp t 'speed', 'stderr.france' u 1:4 w l t 'pieceidx', 'stderr.france' u 1:5 w lp t 'angle', 'stderr.france' u 1:6 w l t 'angular speed', 'stderr.france' u 1:7 w l t 'throttle'
plot 'stderr' u 1:3 w lp t 'speed', 'stderr' u 1:4 w l t 'pieceidx', 'stderr' u 1:5 w lp t 'angle', 'stderr' u 1:6 w l t 'angular speed', 'stderr' u 1:7 w l t 'throttle'
