#!/bin/bash -e

# usage sample: ./racejoin germany pwd 6 sooda

source $(dirname $0)/serverconf
source $(dirname $0)/config
BOTNAME=$4
$(dirname $0)/$PL/plusbot $BOTSERVERNAME $BOTSERVERPORT "$BOTNAME" "$BOTKEY" $1 $2 $3
